# Generated by Django 5.0.1 on 2024-01-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIRLINESAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='fuel_capacity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='airplane',
            name='fuel_consumption',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='airplane_id',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='passenger',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
