# Generated by Django 5.0.1 on 2024-01-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIRLINESAPP', '0002_airplane_fuel_capacity_airplane_fuel_consumption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='fuel_consumption',
        ),
    ]
