# Generated by Django 5.0.1 on 2024-01-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIRLINESAPP', '0005_airplane_fuel_consumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='fuel_capacity',
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='fuel_consumption',
        ),
    ]
