# Generated by Django 5.0.1 on 2024-01-29 04:58

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIRLINESAPP', '0007_airplane_fuel_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirplaneInfo',
            fields=[
                ('airplane_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('passenger_count', models.PositiveIntegerField()),
                ('fuel_capacity_inlitres', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('airplane_id'), '*', models.Value(200)), output_field=models.PositiveIntegerField())),
            ],
        ),
    ]
