# Generated by Django 5.0.1 on 2024-01-31 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIRLINESAPP', '0008_airplaneinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airplane',
        ),
    ]
