[mypy]

plugins = mypy_django_plugin.main , mypy_drf_plugin.main
strict_optional = True

[mypy.plugins.django-stubs]
django_settings_module = "AIRLINES.settings"

[mypy-*.migrations.*]
ignore_errors = True

[mypy-*.models.*]
ignore_errors = True

[mypy-*.settings.*]
ignore_errors = True

[mypy-*.urls.*]
ignore_errors = True


